name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        load: true
        tags: ${{secrets.DOCKER_USER}}/alpine-ssh-client:latest
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag alpine-ssh-client:$(date +%s)
    #- name: Show Images
    #  run: docker images ${{secrets.DOCKER_USER}}/alpine-ssh-client:$(date +%s)
    #- name: Docker Login
    #  env: 
    #    DOCKER_USER: ${{secrets.DOCKER_USER}}
    #    DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
    #  run: echo "${DOCKER_TOKEN}" | docker login -u ${DOCKER_USER} --password-stdin
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/alpine-ssh-client:$(date +%s)
